version: '3.8'

services:
  mongo:
    image: tobnotch/mongo:1.0  # Hämta från DockerHub
    ports:
      - "27017:27017"  # Mappa MongoDB-port
    volumes:
      - mongo_data:/data/db  # Persistenta data
    networks:
      - calcnetwork

  backend:
    image: tobnotch/calculationbackend:1.0  # Hämta från DockerHub
    ports:
      - "8080:8080"  # HTTP-port
      # - "8083:8081"  # HTTPS-port
    # volumes:
    #   - C:/Users/tobia/Desktop:/root/certs  # Montera certifikat från host till rätt sökväg i containern
    environment:
      # ASPNETCORE_URLS: "http://+:8080;https://+:8081"
      # CERT_PASSWORD: "Bytmig123!"  # Certifikatets lösenord för HTTPS
      ASPNETCORE_URLS: "http://+:8080"
      MONGODB_CONNECTION_STRING: "mongodb://mongo:27017/calcdb"  # Anslutningssträng till MongoDB
    networks:
      - calcnetwork
    depends_on:
      - mongo  # Backend startar efter mongo

  frontend:
    image: tobnotch/calculationfrontend:1.0  # Hämta från DockerHub
    ports:
      - "5173:5173"  # React-frontend
    networks:
      - calcnetwork
    depends_on:
      - backend

networks:
  calcnetwork:
    driver: bridge

volumes:
  mongo_data:  # Definiera en volym för MongoDB-data
